// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_slug_ from "./routes/[slug].tsx";
import * as $arxiv_hauls from "./routes/arxiv-hauls.tsx";
import * as $index from "./routes/index.tsx";
import * as $rss_feed from "./routes/rss/feed.tsx";
import * as $rss_topics_slug_ from "./routes/rss/topics/[slug].tsx";
import * as $sitemap_xml from "./routes/sitemap.xml.tsx";
import * as $topics_slug_ from "./routes/topics/[slug].tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $_slug_,
    "./routes/arxiv-hauls.tsx": $arxiv_hauls,
    "./routes/index.tsx": $index,
    "./routes/rss/feed.tsx": $rss_feed,
    "./routes/rss/topics/[slug].tsx": $rss_topics_slug_,
    "./routes/sitemap.xml.tsx": $sitemap_xml,
    "./routes/topics/[slug].tsx": $topics_slug_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
